//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.24 at 06:21:47 PM IST 
//


package com.ecosys.ImportETC;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ecosys.putetchrs package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MSPPutMppDataResult_QNAME = new QName("http://ecosys.net/api/MSPPutMppData", "MSPPutMppDataResult");
    private final static QName _MSPPutMppDataRequest_QNAME = new QName("http://ecosys.net/api/MSPPutMppData", "MSPPutMppDataRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ecosys.putetchrs
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MSPPutMppDataRequestType }
     * 
     */
    public MSPPutMppDataRequestType createMSPPutMppDataRequestType() {
        return new MSPPutMppDataRequestType();
    }

    /**
     * Create an instance of {@link MSPPutMppDataResultType }
     * 
     */
    public MSPPutMppDataResultType createMSPPutMppDataResultType() {
        return new MSPPutMppDataResultType();
    }

    /**
     * Create an instance of {@link PerformanceType }
     * 
     */
    public PerformanceType createPerformanceType() {
        return new PerformanceType();
    }

    /**
     * Create an instance of {@link DocumentValueType }
     * 
     */
    public DocumentValueType createDocumentValueType() {
        return new DocumentValueType();
    }

    /**
     * Create an instance of {@link MSPPutMppDataType }
     * 
     */
    public MSPPutMppDataType createMSPPutMppDataType() {
        return new MSPPutMppDataType();
    }

    /**
     * Create an instance of {@link ErrorType }
     * 
     */
    public ErrorType createErrorType() {
        return new ErrorType();
    }

    /**
     * Create an instance of {@link ResultMessageType }
     * 
     */
    public ResultMessageType createResultMessageType() {
        return new ResultMessageType();
    }

    /**
     * Create an instance of {@link ObjectResultType }
     * 
     */
    public ObjectResultType createObjectResultType() {
        return new ObjectResultType();
    }

    /**
     * Create an instance of {@link DocumentLinkType }
     * 
     */
    public DocumentLinkType createDocumentLinkType() {
        return new DocumentLinkType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MSPPutMppDataResultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ecosys.net/api/MSPPutMppData", name = "MSPPutMppDataResult")
    public JAXBElement<MSPPutMppDataResultType> createMSPPutMppDataResult(MSPPutMppDataResultType value) {
        return new JAXBElement<MSPPutMppDataResultType>(_MSPPutMppDataResult_QNAME, MSPPutMppDataResultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MSPPutMppDataRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ecosys.net/api/MSPPutMppData", name = "MSPPutMppDataRequest")
    public JAXBElement<MSPPutMppDataRequestType> createMSPPutMppDataRequest(MSPPutMppDataRequestType value) {
        return new JAXBElement<MSPPutMppDataRequestType>(_MSPPutMppDataRequest_QNAME, MSPPutMppDataRequestType.class, null, value);
    }

}
