//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.23 at 06:26:59 PM IST 
//


package com.ecosys.getmetcfile;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MSPGetMppFileType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MSPGetMppFileType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CostObjectID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CostObjectName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Attachment" type="{http://ecosys.net/api/MSPGetMppFile}DocumentValueType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MSPGetMppFileType", propOrder = {
    "costObjectID",
    "costObjectName",
    "attachment"
})
public class MSPGetMppFileType {

    @XmlElement(name = "CostObjectID", required = true)
    protected String costObjectID;
    @XmlElement(name = "CostObjectName", required = true)
    protected String costObjectName;
    @XmlElement(name = "Attachment")
    protected DocumentValueType attachment;

    /**
     * Gets the value of the costObjectID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCostObjectID() {
        return costObjectID;
    }

    /**
     * Sets the value of the costObjectID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCostObjectID(String value) {
        this.costObjectID = value;
    }

    /**
     * Gets the value of the costObjectName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCostObjectName() {
        return costObjectName;
    }

    /**
     * Sets the value of the costObjectName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCostObjectName(String value) {
        this.costObjectName = value;
    }

    /**
     * Gets the value of the attachment property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentValueType }
     *     
     */
    public DocumentValueType getAttachment() {
        return attachment;
    }

    /**
     * Sets the value of the attachment property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentValueType }
     *     
     */
    public void setAttachment(DocumentValueType value) {
        this.attachment = value;
    }

}
