//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.23 at 06:26:59 PM IST 
//


package com.ecosys.getmetcfile;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ecosys.getmppfile package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MSPGetMppFileResult_QNAME = new QName("http://ecosys.net/api/MSPGetMppFile", "MSPGetMppFileResult");
    private final static QName _MSPGetMppFileRequest_QNAME = new QName("http://ecosys.net/api/MSPGetMppFile", "MSPGetMppFileRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ecosys.getmppfile
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MSPGetMppFileResultType }
     * 
     */
    public MSPGetMppFileResultType createMSPGetMppFileResultType() {
        return new MSPGetMppFileResultType();
    }

    /**
     * Create an instance of {@link MSPGetMppFileRequestType }
     * 
     */
    public MSPGetMppFileRequestType createMSPGetMppFileRequestType() {
        return new MSPGetMppFileRequestType();
    }

    /**
     * Create an instance of {@link PerformanceType }
     * 
     */
    public PerformanceType createPerformanceType() {
        return new PerformanceType();
    }

    /**
     * Create an instance of {@link DocumentValueType }
     * 
     */
    public DocumentValueType createDocumentValueType() {
        return new DocumentValueType();
    }

    /**
     * Create an instance of {@link MSPGetMppFileType }
     * 
     */
    public MSPGetMppFileType createMSPGetMppFileType() {
        return new MSPGetMppFileType();
    }

    /**
     * Create an instance of {@link ErrorType }
     * 
     */
    public ErrorType createErrorType() {
        return new ErrorType();
    }

    /**
     * Create an instance of {@link ResultMessageType }
     * 
     */
    public ResultMessageType createResultMessageType() {
        return new ResultMessageType();
    }

    /**
     * Create an instance of {@link ObjectResultType }
     * 
     */
    public ObjectResultType createObjectResultType() {
        return new ObjectResultType();
    }

    /**
     * Create an instance of {@link DocumentLinkType }
     * 
     */
    public DocumentLinkType createDocumentLinkType() {
        return new DocumentLinkType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MSPGetMppFileResultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ecosys.net/api/MSPGetMppFile", name = "MSPGetMppFileResult")
    public JAXBElement<MSPGetMppFileResultType> createMSPGetMppFileResult(MSPGetMppFileResultType value) {
        return new JAXBElement<MSPGetMppFileResultType>(_MSPGetMppFileResult_QNAME, MSPGetMppFileResultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MSPGetMppFileRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ecosys.net/api/MSPGetMppFile", name = "MSPGetMppFileRequest")
    public JAXBElement<MSPGetMppFileRequestType> createMSPGetMppFileRequest(MSPGetMppFileRequestType value) {
        return new JAXBElement<MSPGetMppFileRequestType>(_MSPGetMppFileRequest_QNAME, MSPGetMppFileRequestType.class, null, value);
    }

}
