//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.01 at 08:38:22 PM IST 
//


package com.ecosys.ImportProgress;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ecosys.updateprogress package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MSPUpdateProjectProgressResult_QNAME = new QName("http://ecosys.net/api/MSPUpdateProjectProgress", "MSPUpdateProjectProgressResult");
    private final static QName _MSPUpdateProjectProgressRequest_QNAME = new QName("http://ecosys.net/api/MSPUpdateProjectProgress", "MSPUpdateProjectProgressRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ecosys.updateprogress
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MSPUpdateProjectProgressResultType }
     * 
     */
    public MSPUpdateProjectProgressResultType createMSPUpdateProjectProgressResultType() {
        return new MSPUpdateProjectProgressResultType();
    }

    /**
     * Create an instance of {@link MSPUpdateProjectProgressRequestType }
     * 
     */
    public MSPUpdateProjectProgressRequestType createMSPUpdateProjectProgressRequestType() {
        return new MSPUpdateProjectProgressRequestType();
    }

    /**
     * Create an instance of {@link PerformanceType }
     * 
     */
    public PerformanceType createPerformanceType() {
        return new PerformanceType();
    }

    /**
     * Create an instance of {@link DocumentValueType }
     * 
     */
    public DocumentValueType createDocumentValueType() {
        return new DocumentValueType();
    }

    /**
     * Create an instance of {@link ErrorType }
     * 
     */
    public ErrorType createErrorType() {
        return new ErrorType();
    }

    /**
     * Create an instance of {@link MSPUpdateProjectProgressType }
     * 
     */
    public MSPUpdateProjectProgressType createMSPUpdateProjectProgressType() {
        return new MSPUpdateProjectProgressType();
    }

    /**
     * Create an instance of {@link ResultMessageType }
     * 
     */
    public ResultMessageType createResultMessageType() {
        return new ResultMessageType();
    }

    /**
     * Create an instance of {@link ObjectResultType }
     * 
     */
    public ObjectResultType createObjectResultType() {
        return new ObjectResultType();
    }

    /**
     * Create an instance of {@link DocumentLinkType }
     * 
     */
    public DocumentLinkType createDocumentLinkType() {
        return new DocumentLinkType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MSPUpdateProjectProgressResultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ecosys.net/api/MSPUpdateProjectProgress", name = "MSPUpdateProjectProgressResult")
    public JAXBElement<MSPUpdateProjectProgressResultType> createMSPUpdateProjectProgressResult(MSPUpdateProjectProgressResultType value) {
        return new JAXBElement<MSPUpdateProjectProgressResultType>(_MSPUpdateProjectProgressResult_QNAME, MSPUpdateProjectProgressResultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MSPUpdateProjectProgressRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ecosys.net/api/MSPUpdateProjectProgress", name = "MSPUpdateProjectProgressRequest")
    public JAXBElement<MSPUpdateProjectProgressRequestType> createMSPUpdateProjectProgressRequest(MSPUpdateProjectProgressRequestType value) {
        return new JAXBElement<MSPUpdateProjectProgressRequestType>(_MSPUpdateProjectProgressRequest_QNAME, MSPUpdateProjectProgressRequestType.class, null, value);
    }

}
