//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.07 at 03:30:33 PM IST 
//


package com.ecosys.resources;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ecosys.resources package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ResourcesRequest_QNAME = new QName("http://ecosys.net/api/Resources", "ResourcesRequest");
    private final static QName _ResourcesResult_QNAME = new QName("http://ecosys.net/api/Resources", "ResourcesResult");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ecosys.resources
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ResourcesResultType }
     * 
     */
    public ResourcesResultType createResourcesResultType() {
        return new ResourcesResultType();
    }

    /**
     * Create an instance of {@link ResourcesRequestType }
     * 
     */
    public ResourcesRequestType createResourcesRequestType() {
        return new ResourcesRequestType();
    }

    /**
     * Create an instance of {@link PerformanceType }
     * 
     */
    public PerformanceType createPerformanceType() {
        return new PerformanceType();
    }

    /**
     * Create an instance of {@link DocumentValueType }
     * 
     */
    public DocumentValueType createDocumentValueType() {
        return new DocumentValueType();
    }

    /**
     * Create an instance of {@link ResourcesType }
     * 
     */
    public ResourcesType createResourcesType() {
        return new ResourcesType();
    }

    /**
     * Create an instance of {@link ErrorType }
     * 
     */
    public ErrorType createErrorType() {
        return new ErrorType();
    }

    /**
     * Create an instance of {@link ResultMessageType }
     * 
     */
    public ResultMessageType createResultMessageType() {
        return new ResultMessageType();
    }

    /**
     * Create an instance of {@link ObjectResultType }
     * 
     */
    public ObjectResultType createObjectResultType() {
        return new ObjectResultType();
    }

    /**
     * Create an instance of {@link DocumentLinkType }
     * 
     */
    public DocumentLinkType createDocumentLinkType() {
        return new DocumentLinkType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResourcesRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ecosys.net/api/Resources", name = "ResourcesRequest")
    public JAXBElement<ResourcesRequestType> createResourcesRequest(ResourcesRequestType value) {
        return new JAXBElement<ResourcesRequestType>(_ResourcesRequest_QNAME, ResourcesRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResourcesResultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ecosys.net/api/Resources", name = "ResourcesResult")
    public JAXBElement<ResourcesResultType> createResourcesResult(ResourcesResultType value) {
        return new JAXBElement<ResourcesResultType>(_ResourcesResult_QNAME, ResourcesResultType.class, null, value);
    }

}
