//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.07 at 03:30:33 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ecosys.net/api/Resources", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ecosys.resources;
