//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.24 at 06:05:58 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ecosys.net/api/MSPPutMppStructure", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ecosys.putprjwbs;
