//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.23 at 04:04:45 PM IST 
//


package com.ecosys.ImportBudgetDates;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ecosys.ImportBudgetDates package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MSPImportBudgetDatesRequest_QNAME = new QName("http://ecosys.net/api/MSPImportBudgetDates", "MSPImportBudgetDatesRequest");
    private final static QName _MSPImportBudgetDatesResult_QNAME = new QName("http://ecosys.net/api/MSPImportBudgetDates", "MSPImportBudgetDatesResult");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ecosys.ImportBudgetDates
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MSPImportBudgetDatesResultType }
     * 
     */
    public MSPImportBudgetDatesResultType createMSPImportBudgetDatesResultType() {
        return new MSPImportBudgetDatesResultType();
    }

    /**
     * Create an instance of {@link MSPImportBudgetDatesRequestType }
     * 
     */
    public MSPImportBudgetDatesRequestType createMSPImportBudgetDatesRequestType() {
        return new MSPImportBudgetDatesRequestType();
    }

    /**
     * Create an instance of {@link PerformanceType }
     * 
     */
    public PerformanceType createPerformanceType() {
        return new PerformanceType();
    }

    /**
     * Create an instance of {@link DocumentValueType }
     * 
     */
    public DocumentValueType createDocumentValueType() {
        return new DocumentValueType();
    }

    /**
     * Create an instance of {@link ErrorType }
     * 
     */
    public ErrorType createErrorType() {
        return new ErrorType();
    }

    /**
     * Create an instance of {@link MSPImportBudgetDatesType }
     * 
     */
    public MSPImportBudgetDatesType createMSPImportBudgetDatesType() {
        return new MSPImportBudgetDatesType();
    }

    /**
     * Create an instance of {@link ResultMessageType }
     * 
     */
    public ResultMessageType createResultMessageType() {
        return new ResultMessageType();
    }

    /**
     * Create an instance of {@link ObjectResultType }
     * 
     */
    public ObjectResultType createObjectResultType() {
        return new ObjectResultType();
    }

    /**
     * Create an instance of {@link DocumentLinkType }
     * 
     */
    public DocumentLinkType createDocumentLinkType() {
        return new DocumentLinkType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MSPImportBudgetDatesRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ecosys.net/api/MSPImportBudgetDates", name = "MSPImportBudgetDatesRequest")
    public JAXBElement<MSPImportBudgetDatesRequestType> createMSPImportBudgetDatesRequest(MSPImportBudgetDatesRequestType value) {
        return new JAXBElement<MSPImportBudgetDatesRequestType>(_MSPImportBudgetDatesRequest_QNAME, MSPImportBudgetDatesRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MSPImportBudgetDatesResultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ecosys.net/api/MSPImportBudgetDates", name = "MSPImportBudgetDatesResult")
    public JAXBElement<MSPImportBudgetDatesResultType> createMSPImportBudgetDatesResult(MSPImportBudgetDatesResultType value) {
        return new JAXBElement<MSPImportBudgetDatesResultType>(_MSPImportBudgetDatesResult_QNAME, MSPImportBudgetDatesResultType.class, null, value);
    }

}
