//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.23 at 04:04:45 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ecosys.net/api/MSPImportBudgetDates", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ecosys.ImportBudgetDates;
