//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.24 at 11:11:49 AM IST 
//


package com.ecosys.getmprjfile;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ecosys.getmprojectfile package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MSPGetMppFileStructureResult_QNAME = new QName("http://ecosys.net/api/MSPGetMppFileStructure", "MSPGetMppFileStructureResult");
    private final static QName _MSPGetMppFileStructureRequest_QNAME = new QName("http://ecosys.net/api/MSPGetMppFileStructure", "MSPGetMppFileStructureRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ecosys.getmprojectfile
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MSPGetMppFileStructureRequestType }
     * 
     */
    public MSPGetMppFileStructureRequestType createMSPGetMppFileStructureRequestType() {
        return new MSPGetMppFileStructureRequestType();
    }

    /**
     * Create an instance of {@link MSPGetMppFileStructureResultType }
     * 
     */
    public MSPGetMppFileStructureResultType createMSPGetMppFileStructureResultType() {
        return new MSPGetMppFileStructureResultType();
    }

    /**
     * Create an instance of {@link PerformanceType }
     * 
     */
    public PerformanceType createPerformanceType() {
        return new PerformanceType();
    }

    /**
     * Create an instance of {@link DocumentValueType }
     * 
     */
    public DocumentValueType createDocumentValueType() {
        return new DocumentValueType();
    }

    /**
     * Create an instance of {@link MSPGetMppFileStructureType }
     * 
     */
    public MSPGetMppFileStructureType createMSPGetMppFileStructureType() {
        return new MSPGetMppFileStructureType();
    }

    /**
     * Create an instance of {@link ErrorType }
     * 
     */
    public ErrorType createErrorType() {
        return new ErrorType();
    }

    /**
     * Create an instance of {@link ResultMessageType }
     * 
     */
    public ResultMessageType createResultMessageType() {
        return new ResultMessageType();
    }

    /**
     * Create an instance of {@link ObjectResultType }
     * 
     */
    public ObjectResultType createObjectResultType() {
        return new ObjectResultType();
    }

    /**
     * Create an instance of {@link DocumentLinkType }
     * 
     */
    public DocumentLinkType createDocumentLinkType() {
        return new DocumentLinkType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MSPGetMppFileStructureResultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ecosys.net/api/MSPGetMppFileStructure", name = "MSPGetMppFileStructureResult")
    public JAXBElement<MSPGetMppFileStructureResultType> createMSPGetMppFileStructureResult(MSPGetMppFileStructureResultType value) {
        return new JAXBElement<MSPGetMppFileStructureResultType>(_MSPGetMppFileStructureResult_QNAME, MSPGetMppFileStructureResultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MSPGetMppFileStructureRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ecosys.net/api/MSPGetMppFileStructure", name = "MSPGetMppFileStructureRequest")
    public JAXBElement<MSPGetMppFileStructureRequestType> createMSPGetMppFileStructureRequest(MSPGetMppFileStructureRequestType value) {
        return new JAXBElement<MSPGetMppFileStructureRequestType>(_MSPGetMppFileStructureRequest_QNAME, MSPGetMppFileStructureRequestType.class, null, value);
    }

}
